<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prisha Narasimhan">
<meta name="dcterms.date" content="2025-10-15">
<meta name="description" content="  This project built and refined a multiple regression model to understand how factors such as BMI, height, body composition, water intake, workout habits, and demographics influence weight. We applied log transformations, evaluated model assumptions, tested for multicollinearity, interactions, and misspecification, and validated the model through bootstrapping and cross-validation to identify the best-fitting and most reliable specification.">

<title>Economics 103 - Gym Members Exercise Tracking – personal website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">personal website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#model-building" id="toc-model-building" class="nav-link active" data-scroll-target="#model-building">Model Building</a></li>
  <li><a href="#test-for-transformations" id="toc-test-for-transformations" class="nav-link" data-scroll-target="#test-for-transformations">Test for Transformations</a></li>
  <li><a href="#apply-the-3-log-transformations-that-we-found-necessary-earlier." id="toc-apply-the-3-log-transformations-that-we-found-necessary-earlier." class="nav-link" data-scroll-target="#apply-the-3-log-transformations-that-we-found-necessary-earlier.">Apply the 3 log transformations that we found necessary earlier.</a></li>
  <li><a href="#residual-plot-transformed-model" id="toc-residual-plot-transformed-model" class="nav-link" data-scroll-target="#residual-plot-transformed-model">Residual Plot Transformed Model</a></li>
  <li><a href="#qq-plot" id="toc-qq-plot" class="nav-link" data-scroll-target="#qq-plot">QQ Plot</a></li>
  <li><a href="#jarque-bera-test" id="toc-jarque-bera-test" class="nav-link" data-scroll-target="#jarque-bera-test">Jarque Bera Test</a></li>
  <li><a href="#cooks-distance-plot" id="toc-cooks-distance-plot" class="nav-link" data-scroll-target="#cooks-distance-plot">Cook’s Distance Plot</a></li>
  <li><a href="#outlier-and-leverage-diagnostics" id="toc-outlier-and-leverage-diagnostics" class="nav-link" data-scroll-target="#outlier-and-leverage-diagnostics">Outlier and Leverage Diagnostics</a></li>
  <li><a href="#aic-for-model-selection" id="toc-aic-for-model-selection" class="nav-link" data-scroll-target="#aic-for-model-selection">AIC for Model Selection</a></li>
  <li><a href="#bic-for-model-selection" id="toc-bic-for-model-selection" class="nav-link" data-scroll-target="#bic-for-model-selection">BIC for Model Selection</a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">Multicollinearity</a></li>
  <li><a href="#compare-transformed-model-to-original" id="toc-compare-transformed-model-to-original" class="nav-link" data-scroll-target="#compare-transformed-model-to-original">Compare Transformed Model to Original</a></li>
  <li><a href="#model-misspecification-ramsey-reset" id="toc-model-misspecification-ramsey-reset" class="nav-link" data-scroll-target="#model-misspecification-ramsey-reset">Model Misspecification Ramsey Reset</a></li>
  <li><a href="#test-for-interaction-terms" id="toc-test-for-interaction-terms" class="nav-link" data-scroll-target="#test-for-interaction-terms">Test for Interaction Terms</a></li>
  <li><a href="#bootstrapping-log-transformed-model-with-interaction-variable" id="toc-bootstrapping-log-transformed-model-with-interaction-variable" class="nav-link" data-scroll-target="#bootstrapping-log-transformed-model-with-interaction-variable">Bootstrapping Log Transformed Model with Interaction Variable</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">Cross Validation</a></li>
  <li><a href="#check-for-overfitting-since-r-squared-value-is-so-high" id="toc-check-for-overfitting-since-r-squared-value-is-so-high" class="nav-link" data-scroll-target="#check-for-overfitting-since-r-squared-value-is-so-high">Check for Overfitting since R-squared value is so high</a></li>
  <li><a href="#favorite-specification" id="toc-favorite-specification" class="nav-link" data-scroll-target="#favorite-specification">Favorite Specification</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Economics 103 - Gym Members Exercise Tracking</h1>
</div>

<div>
  <div class="description">
    <p><br> This project built and refined a multiple regression model to understand how factors such as BMI, height, body composition, water intake, workout habits, and demographics influence weight. We applied log transformations, evaluated model assumptions, tested for multicollinearity, interactions, and misspecification, and validated the model through bootstrapping and cross-validation to identify the best-fitting and most reliable specification.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prisha Narasimhan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>gym_members_exercise_tracking <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/Econ 103/gym_members_exercise_tracking.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 973 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Gender, Workout_Type
dbl (13): Age, Weight (kg), Height (m), Max_BPM, Avg_BPM, Resting_BPM, Sessi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> gym_members_exercise_tracking</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="model-building" class="level1">
<h1>Model Building</h1>
<p>Basic Multiple Regression Model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Weight (kg)</span><span class="st">`</span> <span class="sc">~</span> BMI <span class="sc">+</span> <span class="st">`</span><span class="at">Height (m)</span><span class="st">`</span> <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>              <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> Gender <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>              Workout_Type, </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-2-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="test-for-transformations" class="level1">
<h1>Test for Transformations</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>gym_members_exercise_tracking<span class="sc">$</span>log_Weight <span class="ot">&lt;-</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(gym_members_exercise_tracking<span class="sc">$</span><span class="st">`</span><span class="at">Weight (kg)</span><span class="st">`</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>gym_members_exercise_tracking<span class="sc">$</span>log_BMI <span class="ot">&lt;-</span> <span class="fu">log</span>(gym_members_exercise_tracking<span class="sc">$</span>BMI)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>gym_members_exercise_tracking<span class="sc">$</span>log_Height <span class="ot">&lt;-</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(gym_members_exercise_tracking<span class="sc">$</span><span class="st">`</span><span class="at">Height (m)</span><span class="st">`</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>model_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                  <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> Gender </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                <span class="sc">+</span> Workout_Type, </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.820e-04 -9.716e-05  5.880e-06  9.825e-05  4.012e-04 

Coefficients:
                             Estimate Std. Error   t value Pr(&gt;|t|)    
(Intercept)                -3.866e-05  9.642e-05    -0.401   0.6885    
log_BMI                     1.000e+00  1.845e-05 54203.765   &lt;2e-16 ***
log_Height                  2.000e+00  7.789e-05 25676.470   &lt;2e-16 ***
Fat_Percentage             -1.021e-07  1.002e-06    -0.102   0.9188    
`Water_Intake (liters)`     9.701e-06  1.067e-05     0.909   0.3633    
`Session_Duration (hours)` -2.476e-06  1.606e-05    -0.154   0.8775    
GenderMale                 -2.850e-05  1.448e-05    -1.969   0.0493 *  
Workout_TypeHIIT           -5.324e-06  1.199e-05    -0.444   0.6570    
Workout_TypeStrength        3.372e-06  1.155e-05     0.292   0.7703    
Workout_TypeYoga            3.388e-06  1.176e-05     0.288   0.7734    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001301 on 963 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.924e+08 on 9 and 963 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="apply-the-3-log-transformations-that-we-found-necessary-earlier." class="level1">
<h1>Apply the 3 log transformations that we found necessary earlier.</h1>
<p>Candidate Model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>can_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                  <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> Gender </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                <span class="sc">+</span> Workout_Type, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>can_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type, data = gym_members_exercise_tracking)

Coefficients:
               (Intercept)                     log_BMI  
                -3.866e-05                   1.000e+00  
                log_Height              Fat_Percentage  
                 2.000e+00                  -1.021e-07  
   `Water_Intake (liters)`  `Session_Duration (hours)`  
                 9.701e-06                  -2.476e-06  
                GenderMale            Workout_TypeHIIT  
                -2.850e-05                  -5.324e-06  
      Workout_TypeStrength            Workout_TypeYoga  
                 3.372e-06                   3.388e-06  </code></pre>
</div>
</div>
<p>Based on the tests run so far, the candidate model accounts for the necessary transformations required on the response and the predictors. With this candidate model, we are trying to find if there is a positive linear relationship between the response variable of weight and the 7 predictors (BMI, height, fat percentage, water intake, session duraction, gender, and workout type). This model is ideally able to take in the appropriately transformed variables and find if in fact there is such positive linear relationship as well as investigate other questions such as if there is multicollinearity between the factor variables and if certain predictors affect weight more than others. The above model is therefore the ideal candidate model to answer such questions.</p>
</section>
<section id="residual-plot-transformed-model" class="level1">
<h1>Residual Plot Transformed Model</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_log, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Residual Plot is randomly scattered around 0, indicating a good plot. Compared to the untransformed data, the residuals of the candidate model appear much more evenly distributed around the horizontal line at 0. However, the only area of concern is that there appears to be a slight narrowing of the residuals as the fitted values increase, hinting that there may be larger variances for smaller values.</p>
</section>
<section id="qq-plot" class="level1">
<h1>QQ Plot</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 868 909</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>No Studentized residuals with Bonferroni p &lt; 0.05
Largest |rstudent|:
    rstudent unadjusted p-value Bonferroni p
909 3.126248          0.0018237           NA</code></pre>
</div>
</div>
<p>QQ Plot follows a straight line in general, indicating a normal distribution. However, 868 and 909 appear to be outliers. However, checking with a Bonferroni outlier test shows that these are not significant outliers.</p>
</section>
<section id="jarque-bera-test" class="level1">
<h1>Jarque Bera Test</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Jarque Bera Test for Untransformed Model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">jarque.bera.test</span>(model<span class="sc">$</span>residuals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Jarque Bera Test

data:  model$residuals
X-squared = 187.81, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Jarque Bera Test for Candidate Model</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">jarque.bera.test</span>(model_log<span class="sc">$</span>residuals) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Jarque Bera Test

data:  model_log$residuals
X-squared = 10.91, df = 2, p-value = 0.004274</code></pre>
</div>
</div>
<p>Using the residual plot for the candidate model, the qq-plot, and the Jarque Bera test, we see that there is no need for further transformations on the candidate model. While the Jarque Bera test p-value is rather low, the p-value for the transformed model is much larger than that of the untransformed model, and furthermore, based on the residual plot we may conclude that there is ultimately no need for further transformation as the scatter is overall random around the horizontal line at 0, indicating a more normal distribution.</p>
</section>
<section id="cooks-distance-plot" class="level1">
<h1>Cook’s Distance Plot</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">influenceIndexPlot</span>(model_log, <span class="at">id=</span><span class="fu">list</span>(<span class="at">n=</span><span class="dv">3</span>), <span class="at">vars =</span> <span class="st">"Cook"</span>, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">main =</span> <span class="st">"Cook's Distance Plot (Top 3 Influential Points)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Cook’s Distance Plot also identifies the same infuential points as the QQ Plot, 868 and 909 as well as point 170.</p>
</section>
<section id="outlier-and-leverage-diagnostics" class="level1">
<h1>Outlier and Leverage Diagnostics</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'olsrr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    rivers</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_resid_lev</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Considering the transformed residual plot, qq plot, Cook’s distance plot, and the Outlier and Leverage Diagnostics, while there are outliers such as points 868, 909, and 170, they would not need to be removed. In the qqplot the outliers outlined are within the 95% confidence interval in addition to the Bonferroni outlier test which demonstrated that these outliers were not significant. Furthermore, as the residual plot of the candidate model is fairly scattered, suggesting that the model assumptions are upheld, the inclusion of the outliers does not appear to distort the overall randomness of the residuals. Therefore, it is reasonable to retain the outliers in this analysis.</p>
</section>
<section id="aic-for-model-selection" class="level1">
<h1>AIC for Model Selection</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(POE5Rdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'POE5Rdata'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    euro</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model_log.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI, <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>model_log.mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>model_log.mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>model_log.mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span>, </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>model_log.mod5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>model_log.mod6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                       Gender, </span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>model_log.mod7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>                       Gender <span class="sc">+</span> Workout_Type, </span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model_log.mod1, model_log.mod2, model_log.mod3, model_log.mod4, </span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    model_log.mod5, model_log.mod6, model_log.mod7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               df         AIC
model_log.mod1  3   -994.0934
model_log.mod2  4 -14647.7960
model_log.mod3  5 -14645.8001
model_log.mod4  6 -14643.8010
model_log.mod5  7 -14641.9933
model_log.mod6  8 -14643.7439
model_log.mod7 11 -14638.4366</code></pre>
</div>
</div>
<p>According to the AIC model, the preferred model is Model 2, which only includes BMI and height.</p>
</section>
<section id="bic-for-model-selection" class="level1">
<h1>BIC for Model Selection</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(POE5Rdata)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>model_log.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI, <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>model_log.mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>model_log.mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage, </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>model_log.mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span>, </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>model_log.mod5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>model_log.mod6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>                       Gender, </span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>model_log.mod7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span> log_BMI <span class="sc">+</span> log_Height <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>                       Gender <span class="sc">+</span> Workout_Type, </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model_log.mod1, model_log.mod2, model_log.mod3, model_log.mod4, </span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    model_log.mod5, model_log.mod6, model_log.mod7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               df         BIC
model_log.mod1  3   -979.4523
model_log.mod2  4 -14628.2745
model_log.mod3  5 -14621.3982
model_log.mod4  6 -14614.5187
model_log.mod5  7 -14607.8306
model_log.mod6  8 -14604.7008
model_log.mod7 11 -14584.7524</code></pre>
</div>
</div>
<p>According to the BIC model, the preferred model is Model 2, which only includes BMI and height.</p>
</section>
<section id="multicollinearity" class="level1">
<h1>Multicollinearity</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               GVIF Df GVIF^(1/(2*Df))
log_BMI                    1.353499  1        1.163400
log_Height                 1.886661  1        1.373558
Fat_Percentage             2.258214  1        1.502735
`Water_Intake (liters)`    2.354351  1        1.534389
`Session_Duration (hours)` 1.743597  1        1.320453
Gender                     3.006329  1        1.733877
Workout_Type               1.022472  3        1.003711</code></pre>
</div>
</div>
<p>Using threshold 4, we keep all variables.</p>
</section>
<section id="compare-transformed-model-to-original" class="level1">
<h1>Compare Transformed Model to Original</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model_original <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">Weight (kg)</span><span class="st">`</span> <span class="sc">~</span> BMI <span class="sc">+</span> <span class="st">`</span><span class="at">Height (m)</span><span class="st">`</span> <span class="sc">+</span> Fat_Percentage <span class="sc">+</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span> <span class="sc">+</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                       Gender <span class="sc">+</span> Workout_Type, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model_original, model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               df        AIC
model_original 11   4559.816
model_log      11 -14638.437</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(model_original, model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               df        BIC
model_original 11   4613.501
model_log      11 -14584.752</code></pre>
</div>
</div>
<p>A Lower AIC and BIC Indicate a better fit compared to the original model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>predicted_log_weight <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_log, gym_members_exercise_tracking)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>actual_log_weight <span class="ot">&lt;-</span> gym_members_exercise_tracking<span class="sc">$</span>log_Weight</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(predicted_log_weight, actual_log_weight, <span class="at">main =</span> <span class="st">"Predicted vs Actual</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="st">     (Log-Transformed Weight)"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Predicted Log Weight"</span>, <span class="at">ylab =</span> <span class="st">"Actual Log Weight"</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Also by visualizing the data we can see that the transformed model does a good job. I tested for multicollinearity by using the VIF method, and based on the threshold of 4, we do not need to remove any of the variables. Furthermore, comparing the AIC and BIC values for the untransformed data to the transformed candidate model, the canidate model seems to have a much better fit as AIC and BIC value is far smaller. Finally, we compared our candidate model to the actual data which was fairly aligned indicating that the model is a good fit of the data.</p>
</section>
<section id="model-misspecification-ramsey-reset" class="level1">
<h1>Model Misspecification Ramsey Reset</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(POE5Rdata)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>reset_test <span class="ot">&lt;-</span> <span class="fu">resettest</span>(model_log, <span class="at">power =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">type =</span> <span class="st">"fitted"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(reset_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  model_log
RESET = 1.1687, df1 = 2, df2 = 961, p-value = 0.3112</code></pre>
</div>
</div>
<p>By running the RESET test, we see that the P-Value of 0.3112 is large enough at the 95% confidence level to fail to reject the null, so a nonlinear term is not needed. This indicates that there is no strong evidence to suggest that important unobserved variables are omitted from the model. Moreover, this implies that the candidate model is likely appropriate for understanding the relationship between the response variable, weight,and the predictor variables.</p>
</section>
<section id="test-for-interaction-terms" class="level1">
<h1>Test for Interaction Terms</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(POE5Rdata)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>model_log1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span>log_BMI<span class="sc">+</span>log_Height<span class="sc">+</span>Fat_Percentage<span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span><span class="sc">+</span> <span class="st">`</span><span class="at">Gender</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Workout_Type</span><span class="st">`</span> <span class="sc">+</span> log_BMI<span class="sc">:</span>log_Height, <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>model_log2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span>log_BMI<span class="sc">+</span>log_Height<span class="sc">+</span>Fat_Percentage<span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span><span class="sc">+</span> <span class="st">`</span><span class="at">Gender</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Workout_Type</span><span class="st">`</span><span class="sc">+</span> log_Height<span class="sc">:</span>Fat_Percentage, <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>model_log3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span>log_BMI<span class="sc">+</span>log_Height<span class="sc">+</span>Fat_Percentage<span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span><span class="sc">+</span> <span class="st">`</span><span class="at">Gender</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Workout_Type</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span><span class="sc">:</span>Fat_Percentage, <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>model_log4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight<span class="sc">~</span>log_BMI<span class="sc">+</span>log_Height<span class="sc">+</span>Fat_Percentage<span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span><span class="sc">+</span> <span class="st">`</span><span class="at">Gender</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Workout_Type</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Gender</span><span class="st">`</span><span class="sc">:</span><span class="st">`</span><span class="at">Workout_Type</span><span class="st">`</span> , <span class="at">data =</span> gym_members_exercise_tracking)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type + log_BMI:log_Height, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.832e-04 -9.782e-05  5.300e-06  9.703e-05  3.803e-04 

Coefficients:
                             Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)                -4.785e-04  4.500e-04   -1.063   0.2879    
log_BMI                     1.000e+00  1.379e-04 7252.725   &lt;2e-16 ***
log_Height                  2.001e+00  7.940e-04 2520.028   &lt;2e-16 ***
Fat_Percentage             -9.340e-08  1.002e-06   -0.093   0.9257    
`Water_Intake (liters)`     9.812e-06  1.067e-05    0.920   0.3579    
`Session_Duration (hours)` -2.831e-06  1.606e-05   -0.176   0.8601    
GenderMale                 -3.046e-05  1.461e-05   -2.085   0.0373 *  
Workout_TypeHIIT           -4.689e-06  1.200e-05   -0.391   0.6961    
Workout_TypeStrength        3.581e-06  1.155e-05    0.310   0.7565    
Workout_TypeYoga            3.955e-06  1.178e-05    0.336   0.7371    
log_BMI:log_Height         -2.459e-04  2.457e-04   -1.001   0.3172    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001301 on 962 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.432e+08 on 10 and 962 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type + log_Height:Fat_Percentage, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.832e-04 -9.723e-05  5.990e-06  9.800e-05  3.976e-04 

Coefficients:
                             Estimate Std. Error   t value Pr(&gt;|t|)    
(Intercept)                 6.600e-05  1.539e-04     0.429   0.6681    
log_BMI                     1.000e+00  1.845e-05 54189.753   &lt;2e-16 ***
log_Height                  2.000e+00  2.338e-04  8553.943   &lt;2e-16 ***
Fat_Percentage             -4.460e-06  5.094e-06    -0.876   0.3815    
`Water_Intake (liters)`     9.809e-06  1.067e-05     0.919   0.3581    
`Session_Duration (hours)` -2.400e-06  1.606e-05    -0.149   0.8812    
GenderMale                 -2.948e-05  1.452e-05    -2.030   0.0427 *  
Workout_TypeHIIT           -5.365e-06  1.199e-05    -0.448   0.6546    
Workout_TypeStrength        3.012e-06  1.156e-05     0.261   0.7944    
Workout_TypeYoga            3.044e-06  1.177e-05     0.259   0.7960    
log_Height:Fat_Percentage   8.036e-06  9.210e-06     0.873   0.3831    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001301 on 962 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.431e+08 on 10 and 962 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type + `Water_Intake (liters)`:Fat_Percentage, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.816e-04 -9.735e-05  5.100e-06  9.679e-05  4.013e-04 

Coefficients:
                                         Estimate Std. Error   t value Pr(&gt;|t|)
(Intercept)                            -5.675e-05  1.310e-04    -0.433   0.6649
log_BMI                                 1.000e+00  1.846e-05 54164.065   &lt;2e-16
log_Height                              2.000e+00  7.801e-05 25638.184   &lt;2e-16
Fat_Percentage                          6.245e-07  3.697e-06     0.169   0.8659
`Water_Intake (liters)`                 1.624e-05  3.376e-05     0.481   0.6306
`Session_Duration (hours)`             -2.959e-06  1.624e-05    -0.182   0.8555
GenderMale                             -2.824e-05  1.454e-05    -1.942   0.0524
Workout_TypeHIIT                       -5.392e-06  1.200e-05    -0.449   0.6532
Workout_TypeStrength                    3.395e-06  1.155e-05     0.294   0.7689
Workout_TypeYoga                        3.451e-06  1.177e-05     0.293   0.7694
Fat_Percentage:`Water_Intake (liters)` -2.544e-07  1.246e-06    -0.204   0.8383
                                          
(Intercept)                               
log_BMI                                ***
log_Height                             ***
Fat_Percentage                            
`Water_Intake (liters)`                   
`Session_Duration (hours)`                
GenderMale                             .  
Workout_TypeHIIT                          
Workout_TypeStrength                      
Workout_TypeYoga                          
Fat_Percentage:`Water_Intake (liters)`    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001301 on 962 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.427e+08 on 10 and 962 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type + Gender:Workout_Type, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.801e-04 -9.750e-05  5.400e-06  9.779e-05  3.999e-04 

Coefficients:
                                  Estimate Std. Error   t value Pr(&gt;|t|)    
(Intercept)                     -3.644e-05  9.693e-05    -0.376    0.707    
log_BMI                          1.000e+00  1.852e-05 53988.484   &lt;2e-16 ***
log_Height                       2.000e+00  7.815e-05 25591.518   &lt;2e-16 ***
Fat_Percentage                  -1.247e-07  1.003e-06    -0.124    0.901    
`Water_Intake (liters)`          9.815e-06  1.068e-05     0.919    0.358    
`Session_Duration (hours)`      -2.958e-06  1.609e-05    -0.184    0.854    
GenderMale                      -2.049e-05  2.002e-05    -1.024    0.306    
Workout_TypeHIIT                -2.160e-06  1.715e-05    -0.126    0.900    
Workout_TypeStrength             1.422e-05  1.656e-05     0.859    0.391    
Workout_TypeYoga                 4.718e-06  1.722e-05     0.274    0.784    
GenderMale:Workout_TypeHIIT     -6.286e-06  2.398e-05    -0.262    0.793    
GenderMale:Workout_TypeStrength -2.103e-05  2.306e-05    -0.912    0.362    
GenderMale:Workout_TypeYoga     -3.148e-06  2.355e-05    -0.134    0.894    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001302 on 960 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 3.685e+08 on 12 and 960 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Using the p-value of coefficients, we see that the model is not statistically significant among the interaction terms, so we won’t need to include them.</p>
</section>
<section id="bootstrapping-log-transformed-model-with-interaction-variable" class="level1">
<h1>Bootstrapping Log Transformed Model with Interaction Variable</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'boot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:POE5Rdata':

    tuna</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    logit</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>bootstrap_function <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  resampled_data <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  model_resampled <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">*</span> Fat_Percentage <span class="sc">+</span> log_Height <span class="sc">+</span> </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> resampled_data)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">coef</span>(model_resampled))  }</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>boot_results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> gym_members_exercise_tracking, <span class="at">statistic =</span> bootstrap_function, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>boot_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = gym_members_exercise_tracking, statistic = bootstrap_function, 
    R = 1000)


Bootstrap Statistics :
         original        bias     std. error
t1* -5.882657e-04 -8.554770e-06 3.014201e-04
t2*  1.000187e+00  2.631089e-06 8.886319e-05
t3*  2.423869e-05  2.404932e-07 1.133134e-05
t4*  1.999968e+00  8.871506e-07 6.440787e-05
t5* -1.338986e-06 -5.953335e-08 9.266424e-06
t6*  7.157967e-06 -1.077169e-07 1.619223e-05
t7* -7.503450e-06 -7.659321e-08 3.458305e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(boot_results<span class="sc">$</span>t) <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">coef</span>(<span class="fu">lm</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">*</span> Fat_Percentage <span class="sc">+</span> log_Height <span class="sc">+</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">data =</span> gym_members_exercise_tracking)))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>interaction_coefficients <span class="ot">&lt;-</span> boot_results<span class="sc">$</span>t[, <span class="st">"log_BMI:Fat_Percentage"</span>]</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(interaction_coefficients, </span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution of log_BMI:Fat_Percentage Interaction Coefficient"</span>, </span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Interaction Coefficient (log_BMI:Fat_Percentage)"</span>, </span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lightblue"</span>, </span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"black"</span>, </span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Histogram looks fairly symmetric and normally distributed. Based on this histogram, the sampling distribution of the predictors are overall approximately normal, which suggests that the inference methods relying on normality may still be reasonably robust.</p>
</section>
<section id="cross-validation" class="level1">
<h1>Cross Validation</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(caret)) <span class="fu">install.packages</span>(<span class="st">"caret"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: caret</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lattice'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:boot':

    melanoma</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>cv_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>cv_model <span class="ot">&lt;-</span> <span class="fu">train</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">*</span> Fat_Percentage <span class="sc">+</span> log_Height <span class="sc">+</span> </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>                  <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> gym_members_exercise_tracking, </span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"lm"</span>,  </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl =</span> cv_control)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cv_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

973 samples
  5 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 875, 874, 876, 876, 876, 876, ... 
Resampling results:

  RMSE          Rsquared   MAE         
  0.0001299402  0.9999998  0.0001083176

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Cross-Validated RMSE:"</span>, cv_model<span class="sc">$</span>results<span class="sc">$</span>RMSE, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated RMSE: 0.0001299402 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Cross-Validated R-Squared:"</span>, cv_model<span class="sc">$</span>results<span class="sc">$</span>Rsquared, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated R-Squared: 0.9999998 </code></pre>
</div>
</div>
<p>RMSE of 0.0001299402 suggests that the model’s predictions of log_Weight deviate only slightly from the observed values. An R-squared value of 0.9999998 means that nearly all the variability in log_Weight is explained by the predictors, including the interaction term. A MAE of 0.0001083176 is very close to zero, further confirming the model’s strong predictive power.</p>
</section>
<section id="check-for-overfitting-since-r-squared-value-is-so-high" class="level1">
<h1>Check for Overfitting since R-squared value is so high</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>train_indices <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(gym_members_exercise_tracking<span class="sc">$</span>log_Weight, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> gym_members_exercise_tracking[train_indices, ]</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>testing_data <span class="ot">&lt;-</span> gym_members_exercise_tracking[<span class="sc">-</span>train_indices, ]</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>model_train <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Weight <span class="sc">~</span> log_BMI <span class="sc">*</span> Fat_Percentage <span class="sc">+</span> log_Height <span class="sc">+</span> </span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>                  <span class="st">`</span><span class="at">Water_Intake (liters)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">Session_Duration (hours)</span><span class="st">`</span>, </span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> training_data)</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>train_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_train, <span class="at">newdata =</span> training_data)</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>train_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((train_predictions <span class="sc">-</span> training_data<span class="sc">$</span>log_Weight)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>train_r2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>((train_predictions <span class="sc">-</span> training_data<span class="sc">$</span>log_Weight)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> </span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>                <span class="fu">sum</span>((training_data<span class="sc">$</span>log_Weight <span class="sc">-</span> <span class="fu">mean</span>(training_data<span class="sc">$</span>log_Weight))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training RMSE:"</span>, train_rmse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training RMSE: 0.0001309695 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training R²:"</span>, train_r2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training R²: 0.9999998 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>test_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_train, <span class="at">newdata =</span> testing_data)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>test_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_predictions <span class="sc">-</span> testing_data<span class="sc">$</span>log_Weight)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>test_r2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>((test_predictions <span class="sc">-</span> testing_data<span class="sc">$</span>log_Weight)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">sum</span>((testing_data<span class="sc">$</span>log_Weight <span class="sc">-</span> <span class="fu">mean</span>(testing_data<span class="sc">$</span>log_Weight))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Test RMSE:"</span>, test_rmse, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test RMSE: 0.0001237238 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Test R²:"</span>, test_r2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test R²: 0.9999998 </code></pre>
</div>
</div>
<p>The slightly lower RMSE on the test set (0.0001237238) suggests that the model generalizes very well to unseen data and does not overfit. The identical R² values for both the training and test sets suggest that the model performs equally well on unseen data as it does on the data it was trained on, confirming no signs of overfitting.</p>
</section>
<section id="favorite-specification" class="level1">
<h1>Favorite Specification</h1>
<p>In our analysis, using the Jarque Bera test, the qq plot, and the residual plot of the candidate model, we found that there is no need for further transformations on our model. Based on the Cook’s Distance plot, the Outlier and Leverage Diagnostic plot, with inferences from the residual plot, we noted that while there are outliers in our model, they do not need to be removed. Using the AIC and BIC model, along with the VIF method, we tested for multicollinearity and noted that no variables needed to be removed. To test model misspecification, we ran the RESET test and as the p-value was not statistically significant, we concluded that nonlinear terms were not needed in the model. We additionally tested interactions between variables and found that there were no significant interactions to include amongst the ones tested. Finally, using the boostrap method, the resulting histogram was overall normally distributed resulting in a reasonable amount of robustness. A preferred form of analysis was the RESET test, as it’s p-value indicated whether nonlinear terms were needed in the model, and furthermore if there were any unobserved omitted variables (which may have been the cause if the p-value was below 0.05). This test incorporates our understanding of the p-value to test specific characteristics on the model and encourage changes such as a quardratic variable or to think further about unobserved variables when the p-value is significant.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + 
    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + 
    Workout_Type, data = gym_members_exercise_tracking)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.820e-04 -9.716e-05  5.880e-06  9.825e-05  4.012e-04 

Coefficients:
                             Estimate Std. Error   t value Pr(&gt;|t|)    
(Intercept)                -3.866e-05  9.642e-05    -0.401   0.6885    
log_BMI                     1.000e+00  1.845e-05 54203.765   &lt;2e-16 ***
log_Height                  2.000e+00  7.789e-05 25676.470   &lt;2e-16 ***
Fat_Percentage             -1.021e-07  1.002e-06    -0.102   0.9188    
`Water_Intake (liters)`     9.701e-06  1.067e-05     0.909   0.3633    
`Session_Duration (hours)` -2.476e-06  1.606e-05    -0.154   0.8775    
GenderMale                 -2.850e-05  1.448e-05    -1.969   0.0493 *  
Workout_TypeHIIT           -5.324e-06  1.199e-05    -0.444   0.6570    
Workout_TypeStrength        3.372e-06  1.155e-05     0.292   0.7703    
Workout_TypeYoga            3.388e-06  1.176e-05     0.288   0.7734    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0001301 on 963 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.924e+08 on 9 and 963 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Upon building and testing our model through various forms of analysis, we may now use it to help answer some of our motivating questions. Using the estimated values shown in the above summary of our model, we are able to observe whether there is a linear relationship between our reponse variable weight, and each of the seven predictors. We notice that BMI and Height have a positive linear relationship with weight therefore the marginal effect from an increase in either of these variables will have an increase in weight as well. This may be due to the fact that BMI and Height have a direct relationship with weight as BMI times Height (m)^2 is equal to weight, indicating a direct positive relationship. BMI and Height therefore seem to have a stronger relationship to weight, which is further assured by AIC and BIC models in which the preferred model included only BMI and Height. Additionally, from our model, we observe that Water Intake (liters), Strength Workouts and Yoga Workout, have a positive linear relationship with weight (based on their marginal effects), suggesting that increased water intake, a higher frequency of strength and yoga workouts may be associated with higher weight when considered marginally. Fat percentage, gender (male), Session duration, and HIIT Workout have negative marginal effects in relation to weight. This suggests that these variables are associated with reductions in weight when considered marginally.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>© 2025, Prisha Narasimhan</p>
</div>
  </div>
</footer>




</body></html>