{
  "hash": "14dfe020086bf7fe52774f4cd3006dbe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Economics 104 - Natural Gas Panel Dataset\"\nimage: ../natural_gas.png\nauthor: \"Prisha Narasimhan\"\ndate: \"2025-10-15\"\noutput:\n  pdf_document: default\n  html_document: default\ndescription: |\n  <br>\n  This project analyzes residential natural gas consumption across five U.S. states (NY, FL, MI, TX, CA) from 1967–1989 using panel data techniques. I explored how energy prices, heating degree days, and per-capita income affect consumption, comparing pooled, fixed-effects, and random-effects models. Diagnostics, heterogeneity tests, and model selection procedures were applied to identify the preferred two-way fixed effects model, providing insights into the influence of climate, prices, and income on gas consumption.\n---  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"NaturalGas\")\n\nnatural_gas <- subset(NaturalGas, state == \"NY\" |\n                        state == \"FL\" | state == \"MI\" | state == \"TX\" | state == \"CA\")\n\nnatural_gas_pd <- pdata.frame(natural_gas, index = c(\"state\", \"year\"))\nclass(natural_gas_pd) # make sure it's a panel data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"pdata.frame\" \"data.frame\" \n```\n\n\n:::\n\n```{.r .cell-code}\ndim(natural_gas_pd) # dimension\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 115  10\n```\n\n\n:::\n\n```{.r .cell-code}\nis.pbalanced(natural_gas_pd) # is it balanced\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n# a. Data Discussion\n\nBriefly discuss the question you are trying to answer.\n\nFor this panel data projet, we're using the Natural Gas dataset from the AERpackage in R, which contains 115 observations from 5 US states over the period 1967-1989. The source of the data is from Baltagi (2002). The dataset includes variables such as consumption (consumption of natural gas by the residential sector), price (the price of natural gas), eprice, (price of electricity), oprice (price of distillate fuel oil), lprice (price of liquefied petroleum gas), heating (heating degree days), and income (real per-capita personal income). Specifically, the question we are trying to answer is: How do prices (of natural gas, electricity, distillate fuel oil, and liquefied petroleum gas),heating degree days, and personal income affect consumption of natural gas? The dimensions of the panel dataset is 115 rows and 10 columns and is therefore long and narrow. The panel dataset is balanced. \n\nThe citation of the dataset is: Baltagi, B.H. (2002). Econometrics, 3rd ed. Berlin, Springer.\n\n# b. Variable Description\n\nProvide a descriptive analysis of your variables. This should include \nrelevant figures with comments including some graphical depiction of individual\nhetero-geneity; no unnecessary figures!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# histograms for each variable\npar(mfrow = c(2,2))\nhist(natural_gas_pd$consumption, main = \"Histogram of Consumption\")\nhist(natural_gas_pd$price, main = \"Histogram of Price\")\nhist(natural_gas_pd$eprice, main = \"Histogram of ePrice\")\nhist(natural_gas_pd$oprice, main = \"Histogram of oPrice\")\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-3-1.png){fig-pos='!H' width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2,2))\nhist(natural_gas_pd$lprice, main = \"Histogram of lPrice\")\nhist(natural_gas_pd$heating, main = \"Histogram of Heating\")\nhist(natural_gas_pd$income, main = \"Histogram of Income\")\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-3-2.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nI ran histograms for each feature and the response in the case of an extreme right skew. In which case, we would implement the log of the variable to better adhere to the linear regression assumptions. From the plots we see that while there are some moderate right skews, none of which are rather extreme, and therefore, we will not need to log transform the respective variables. \n\nConsumption: Residential gas consumption is somewhat normal and however, has a second peak towards the left tail. The two peaks are between 0 and 50,000 and 300,000 and 350,000, suggesting that these are perhaps the more common ranges for annual residential gas consumption across states. The range of the data is between 0 to 65,000 with limited to no outliers observed. \n\nPrice: The price of natural gas is slightly right-skewed, indicating that while the price of natural gas has been relatively low across most state-years, there have been a few instances of higher prices. The peak occurs around 1 to 2, suggesting that this is the common range of prices for natural gas across states. The range of prices is from 0 to 9 with limited to no outliers observed.\n\nePrice: The price of electricity is slightly right-skewed, indicating that while the price of electricity has been relatively lower across most state-years, there have been a few instances of higher electricity prices. The peak occurs around 2 to 3, suggesting that this is the common range of prices for electricity across states. The range of prices for electricity is from 1 to 11 with limited to no outliers observed.\n\noPrice: The price of distillate fuel oil is very slightly right-skewed, indicating that while the price of distillate fuel oil has been somewhat relatively lower across most state-years, there have been fewer years of higher distillate fuel oil prices as well. The peak occurs around 5 to 10, suggesting that this is the most common range of prices for distillate fuel oil. The range of prices is from 5 to 55 with limited to no outliers observed.\n\nlPrice: The price of liquefied petroleum gas has a very slight right-skew, indicating that while the price of liquefied petroleum gas has been somewhat relatively lower across most state-years, there have been fewer years of higher liquefied petroleum gas as well. The peak occurs around 1 to 2, suggesting that this is the common range of prices for liquefied petroleum gas. The range of prices is from 0 to 8 with limited to no outliers observed.\n\nHeating: Heating degree days looks to have a bi-modal distribution with two peaks from 2000 to 3000, and 6000 to 7000, suggesting that these are perhaps the more common ranges for heating degree days across states. The range of data is between 0 to 8000 with limited to no outliers observed.\n\nIncome: Income across all states and years is approximately normally distributed, indicating that most state-year observations cluster around a central average, with fewer very low or very high values. There is no strong skew, and extreme outliers seem limited.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(consumption ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-4-1.png){fig-pos='!H' width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"24\"  \"35\"  \"57\"  \"60\"  \"104\" \"105\"\n```\n\n\n:::\n:::\n\n\nFrom the scatterplot of consumption across states, we see a varying range of the data, with California having the largest range and Florida seemingly have the shortest. Additionally, the means with respect to the level of consumption indicates rather varying level of consumption per state. Therefore, both the average level of consumption and the range of consumption seem different across states, suggesting individual heterogeneity. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(price ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-5-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nFrom the scatterplot of the price of natural gas across states, we see a similar price range of the data, and somewhat similar average price levels as well. Based on the similar price levels and ranges across states, this scatterplot therefore does not suggest individual heterogeneity, though further testing is necessary.\n \n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(eprice ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-6-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nFrom the scatterplot of the price of electricity across states, we see a slightly varying price range of the data, and however, somewhat similar average price levels. Based on the similar price levels and slightly varying ranges across states, this scatterplot does not suggest individual heterogeneity, though further testing is necessary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(oprice ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-7-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nFrom the scatterplot of the price of distillate fuel oil across states, we see a similar price range of the data, and similar average price levels. Based on the similar price levels and ranges across states, this scatterplot does notsuggest individual heterogeneity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(lprice ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-8-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nFrom the scatterplot of the price of liquefied petroleum gas, we see a similar price range of the data, and somewhat varying average price levels. Based on the similar price levels and slightly varying ranges across states, this scatterplot therefore does not suggest individual heterogeneity, however further testing is necessay.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(heating ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-9-1.png){fig-pos='!H' width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"53\" \"67\"\n```\n\n\n:::\n:::\n\n\nFrom the scatterplot of heating degree days, we see a similar range of the data across states. Additionally, the means with respect to the level of heating indicates an extremely varying level of heating degree days per state. Therefore, while the range of the level of heating is rather similar across states, the average level greatly varies, suggesting indivdual heterogeneity, though further testing is necessary. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nscatterplot(income ~ state | year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-10-1.png){fig-pos='!H' width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"91\" \"92\"\n```\n\n\n:::\n:::\n\n\nFrom the scatterplot of per-capita personal income, we see varying ranges of the data across states. Additionally, the means with respect to the level of income indicates an moderate level of variation of income per state. Therefore, while the range and price of the level of income moderately vary, individual heterogeneity is suggested, though further testing is necessary.  \n\nBased on the analysis of the observable variables, it is suggested that individual heterogeneity may be present in the model, alluding to the fact the differences may be attributed to factors or variables that are unobserved or unaccounted for. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotmeans(consumption ~ state, data = natural_gas_pd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in arrows(x, li, x, pmax(y - gap, li), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, li, x, pmax(y - gap, li), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, li, x, pmax(y - gap, li), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, li, x, pmax(y - gap, li), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, li, x, pmax(y - gap, li), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in arrows(x, ui, x, pmin(y + gap, ui), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, ui, x, pmin(y + gap, ui), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, ui, x, pmin(y + gap, ui), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, ui, x, pmin(y + gap, ui), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\nWarning in arrows(x, ui, x, pmin(y + gap, ui), col = barcol, lwd = lwd, :\nzero-length arrow is of indeterminate angle and so skipped\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-11-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nThe above plot indicates that across each unit (states), there are differences in the average level of consumption of natural gas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotmeans(consumption ~ year, data = natural_gas_pd)\n```\n\n::: {.cell-output-display}\n![](03-project_files/figure-html/unnamed-chunk-12-1.png){fig-pos='!H' width=672}\n:::\n:::\n\n\nThe above plot suggests that overtime, the average level of consumption doesn't seem to fluctuate much. Additionally, the range also seems to be of a constant size over time. From the plot, statistical insignificance of the differnce maybe be suggested but further testing is necessary to make such a conclusion. Overall, while there may be consistency across the years, there seems to be significant individual differences across states.\n\n# c. Model Fitting\n\nc.Fit the three models below, and identify which model is your preferred one and why. Make sure to include your statistical diagnostics to support your conclusion, and to comment on your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npooledreg1 <- plm(consumption~price+eprice+oprice+lprice+heating+income,\n                  model=\"pooling\",data=natural_gas_pd)\n\n# Cluster robust standard errors\ncrse<- coeftest(pooledreg1, vcov=vcovHC(pooledreg1,\ntype=\"HC0\",cluster=\"group\"))\n\nstargazer(pooledreg1, crse, column.labels = c(\"\\\\textit{Pooled}\", \n                                              \"\\\\textit{Pooled(prse)}\"),\n        model.names = FALSE,type = \"text\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n====================================================\n                       Dependent variable:          \n             ---------------------------------------\n                   consumption                      \n                     Pooled           Pooled(prse)  \n                       (1)                 (2)      \n----------------------------------------------------\nprice            -104,163.000***     -104,163.000***\n                  (34,055.000)        (21,477.000)  \n                                                    \neprice             27,709.000*         27,709.000   \n                  (15,928.000)        (28,194.000)  \n                                                    \noprice             3,868.000**         3,868.000**  \n                   (1,550.000)         (1,841.000)  \n                                                    \nlprice             -15,593.000         -15,593.000  \n                  (29,488.000)        (16,149.000)  \n                                                    \nheating               5.112               5.112     \n                     (4.627)             (7.634)    \n                                                    \nincome              85.770***           85.770***   \n                     (9.856)            (27.520)    \n                                                    \nConstant         -538,137.000***     -538,137.000** \n                  (89,926.000)        (207,779.000) \n                                                    \n----------------------------------------------------\nObservations           115                          \nR2                    0.727                         \nAdjusted R2           0.711                         \nF Statistic  47.830*** (df = 6; 108)                \n====================================================\nNote:                    *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\nThe coefficients from the pooled model may be interpretted as such: A one-unit increase in the price of natural gas is associated with a 104,163 unit decrease in natural gas consumption, on average, across all states and years. A one-unit increase in the price of electricity is associated with a 27,709 unit increase in electricity consumption, on average, across all states and years. A one-unit increase in the price of distillate fuel oil is associated with a 3,868 unit increase in distillate fuel oil consumption, on average, across all states and years. A one-unit increase in the price of liquefied petroleum gas is associated with a 15,593 unit decrease in distillate fuel oil consumption, on average, across all states and years. A one-unit increase in the heating degree days is associated with a 5.112 unit increase in consumption, on average, across all states and years. A one-unit increase in the per-capita personal income is associated with a 85.77 unit increase in consumption, on average, across all states and years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fixed effect model: one way (individual)\nwithinreg1 <- plm(consumption~price+eprice+oprice+lprice+heating+income, model=\"within\", effect = \"individual\", data=natural_gas_pd)\nsummary(withinreg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = consumption ~ price + eprice + oprice + lprice + \n    heating + income, data = natural_gas_pd, effect = \"individual\", \n    model = \"within\")\n\nBalanced Panel: n = 5, T = 23, N = 115\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n -66534  -12662     214   11717   80863 \n\nCoefficients:\n        Estimate Std. Error t-value Pr(>|t|)    \nprice    8550.60    9935.04    0.86    0.391    \neprice  -7366.93    5722.26   -1.29    0.201    \noprice     75.25     490.75    0.15    0.878    \nlprice  -7267.64    8547.89   -0.85    0.397    \nheating    46.93      10.45    4.49 0.000018 ***\nincome      6.75       3.96    1.71    0.091 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    8.89e+10\nResidual Sum of Squares: 6.63e+10\nR-Squared:      0.254\nAdj. R-Squared: 0.183\nF-statistic: 5.91678 on 6 and 104 DF, p-value: 0.0000241\n```\n\n\n:::\n:::\n\n\nThis model accounts for individual effects. We may conclude that generally (and the term generally may be applied to all other coefficient interpretations for this set of comments) there is 8550.60 increase in the level of consumption when the price of natural gas increases by 1 unit. There is 7366.93 decrease in the level of consumption when the price of electricity increases by one unit. There is a 75.25 increase in the level of consumption when the price of distillate fuel oil increases by one unit. There is a 7267.64 decrease in the level of consumption when the price of liquefied petroleum gas increases by one unit. There is a 46.93 increase in the level of consumption when heating degree days increaes by one unit. And there is a 6.75 increase in the level of consumption when per-capita personal income increases by one unit. This is the result within each state once accounting for the differences between states.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fixed effect model: one way (time)\nwithinreg2 <- plm(consumption~price+eprice+oprice+lprice+heating+income, model=\"within\", effect = \"time\", data=natural_gas_pd)\nsummary(withinreg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (time) effect Within Model\n\nCall:\nplm(formula = consumption ~ price + eprice + oprice + lprice + \n    heating + income, data = natural_gas_pd, effect = \"time\", \n    model = \"within\")\n\nBalanced Panel: n = 5, T = 23, N = 115\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n-114033  -43894   -1522   50755  163319 \n\nCoefficients:\n         Estimate Std. Error t-value Pr(>|t|)    \nprice   -7.24e+04   3.67e+04   -1.97   0.0517 .  \neprice   3.68e+04   1.37e+04    2.68   0.0088 ** \noprice   2.89e+03   3.21e+03    0.90   0.3719    \nlprice  -1.08e+05   3.79e+04   -2.84   0.0056 ** \nheating  4.02e-01   3.95e+00    0.10   0.9190    \nincome   9.00e+01   9.59e+00    9.38  8.1e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    3.5e+12\nResidual Sum of Squares: 4.99e+11\nR-Squared:      0.857\nAdj. R-Squared: 0.811\nF-statistic: 86.0979 on 6 and 86 DF, p-value: <2e-16\n```\n\n\n:::\n:::\n\n\nThis model accounts for time effects. We may conclude that generally (and the term generally may be applied to all other coefficient interpretations for this set of comments) there is 7.24e+04 decrease in the level of consumption when the price of natural gas increases by 1 unit. There is 3.68e+04 increase in the level of consumption when the price of electricity increases by one unit. There is a 2.89e+03 increase in the level of consumption when the price of distillate fuel oil increases by one unit. There is a 1.08e+05 decrease in the level of consumption when the price of liquefied petroleum gas increases by one unit. There is a 4.02e-01 increase in the level of consumption when heating degree days increase by one unit. And there is a 9.00e+01 increase in the level of consumption when per-capita personal income increases by one unit. This is the result within each year once accounting for the differences across time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fixed effect model: twoways\nwithinreg3 <- plm(consumption~price+eprice+oprice+lprice+heating+income, model=\"within\", effect = \"twoways\", data=natural_gas_pd)\nsummary(withinreg3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects Within Model\n\nCall:\nplm(formula = consumption ~ price + eprice + oprice + lprice + \n    heating + income, data = natural_gas_pd, effect = \"twoways\", \n    model = \"within\")\n\nBalanced Panel: n = 5, T = 23, N = 115\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n -60442  -11674    -136   12153   56993 \n\nCoefficients:\n        Estimate Std. Error t-value Pr(>|t|)    \nprice   12557.58   11579.83    1.08     0.28    \neprice  -8425.45    5926.83   -1.42     0.16    \noprice    803.70    1000.90    0.80     0.42    \nlprice  12545.43   12460.36    1.01     0.32    \nheating    60.55      11.03    5.49  4.4e-07 ***\nincome     -2.03       5.67   -0.36     0.72    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    6.12e+10\nResidual Sum of Squares: 4.16e+10\nR-Squared:      0.32\nAdj. R-Squared: 0.0544\nF-statistic: 6.42587 on 6 and 82 DF, p-value: 0.000014\n```\n\n\n:::\n:::\n\n\nThis model accounts for two-ways (individual and time) effects. We may conclude that generally (and the term generally may be applied to all other coefficient interpretations for this set of comments) there is 12557.58 increase in the level of consumption when the price of natural gas increases by 1 unit. There is 8425.45 decrease in the level of consumption when the price of electricity increases by one unit. There is a 803.7 increase in the level of consumption when the price of distillate fuel oil increases by one unit. There is a 12545.43 increase in the level of consumption when the price of liquefied petroleum gas increases by one unit. There is a 60.55 increase in the level of consumption when heating degree days increase by one unit. And there is a 2.03 decrease in the level of consumption when per-capita personal income increases by one unit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npFtest(withinreg1, pooledreg1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for individual effects\n\ndata:  consumption ~ price + eprice + oprice + lprice + heating + income\nF = 352, df1 = 4, df2 = 104, p-value <2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n\n```{.r .cell-code}\n# we reject the null so there seems like there are individual effects\n```\n:::\n\n\nWe have implemented the F-test for individual effects. The null hypothesis is that there are no individual effects and the alternate hypothesis states that there are effects and we must use a model that accounts for these differences across individuals. We reject the null, indicating that there may be individual effects. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npFtest(withinreg2, pooledreg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for time effects\n\ndata:  consumption ~ price + eprice + oprice + lprice + heating + income\nF = 3.6, df1 = 22, df2 = 86, p-value = 9e-06\nalternative hypothesis: significant effects\n```\n\n\n:::\n\n```{.r .cell-code}\n# we reject the null so there seems to be time effects as well.\n```\n:::\n\n\nWe have implemented the F-test for time effects. From the p-value, we reject the null hypothesis that there are no time effects and conclude that there may be time effects and we must use a model that accounts for these differences across years. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Random effects model\nrandom_effects <- plm(consumption ~ price + eprice  + oprice + lprice + heating + income, data=natural_gas_pd, model=\"random\", random.method = \"amemiya\")\n\nsummary(random_effects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Random Effect Model \n   (Amemiya's transformation)\n\nCall:\nplm(formula = consumption ~ price + eprice + oprice + lprice + \n    heating + income, data = natural_gas_pd, model = \"random\", \n    random.method = \"amemiya\")\n\nBalanced Panel: n = 5, T = 23, N = 115\n\nEffects:\n                   var  std.dev share\nidiosyncratic 6.02e+08 2.45e+04  0.02\nindividual    2.41e+10 1.55e+05  0.98\ntheta: 0.967\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n -56760  -14490   -1843    9973   90718 \n\nCoefficients:\n            Estimate Std. Error z-value Pr(>|z|)    \n(Intercept) 75764.96   87364.23    0.87    0.386    \nprice        8422.00    9959.54    0.85    0.398    \neprice      -7279.27    5735.91   -1.27    0.204    \noprice         81.31     492.19    0.17    0.869    \nlprice      -7525.80    8569.24   -0.88    0.380    \nheating        45.26       9.92    4.56    5e-06 ***\nincome          7.08       3.97    1.79    0.074 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    9.26e+10\nResidual Sum of Squares: 6.92e+10\nR-Squared:      0.252\nAdj. R-Squared: 0.211\nChisq: 36.4203 on 6 DF, p-value: 2.28e-06\n```\n\n\n:::\n:::\n\n\nFrom the Random effects model, we may interpret the variables as such: For a 1 increase in the price of natural gas, as associate a 8422 unit increase in gas consumption. For a 1 unit increase in the price of electricity, we expect a 7279.27 unit decrease in gas consumption. For a 1 unit increase in the price of distillate fuel oil, we associate a 81.31 unit increase in gas consumption. For a 1 unit increase in the price of liquefied petroleum gas, we associate a 7525.8 unit decrease in gas consumption. For a 1 unit increase in the heating degree days, we associate a 45.26 unit increase in gas consumption. Finally, for a 1 unit icnrease in income, we associate a 7.08 unit increase in gas consumption. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Random Effects Test\nconsumptionReTest <- plmtest(pooledreg1, effect=\"twoways\")\nconsumptionReTest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLagrange Multiplier Test - two-ways effects (Honda)\n\ndata:  consumption ~ price + eprice + oprice + lprice + heating + income\nnormal = 9.9, p-value <2e-16\nalternative hypothesis: significant effects\n```\n\n\n:::\n:::\n\n\nThe LM test shows that the null hypothesis of zero variance in the two-way specifc errors (of indvidiuals and time) is rejected; therefore, heterogeneity among individuals and time may be significant. Therefore, we should not use the pooled model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compared fixed effects (two-ways) and REM\nphtest(withinreg3, random_effects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHausman Test\n\ndata:  consumption ~ price + eprice + oprice + lprice + heating + income\nchisq = 28, df = 6, p-value = 0.0001\nalternative hypothesis: one model is inconsistent\n```\n\n\n:::\n:::\n\n\nFrom the Hausman Test, our p-value is well less than alpha = 0.05, and therefore we reject the null, which implies that one model is inconsistent and we implement the twoway fixed effect model as our preferred model. As we are to use the fixed effects, we would likely want to use the Hausman Taylor estimators, though we must ensure that we have enough instruments. The number of time-varying variables should be at least as much as the number of time-invariant variables.\n\n\\section{d. Conclusion}\n\nDiscuss the potential real-world implications of your findings or possible applications. (eg. How might it inform a policy decision or translate to earning potential;how would this be quantified?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithinreg3 <- plm(consumption~price+eprice+oprice+lprice+heating+income, model=\"within\", effect = \"twoways\", data=natural_gas_pd)\nsummary(withinreg3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects Within Model\n\nCall:\nplm(formula = consumption ~ price + eprice + oprice + lprice + \n    heating + income, data = natural_gas_pd, effect = \"twoways\", \n    model = \"within\")\n\nBalanced Panel: n = 5, T = 23, N = 115\n\nResiduals:\n   Min. 1st Qu.  Median 3rd Qu.    Max. \n -60442  -11674    -136   12153   56993 \n\nCoefficients:\n        Estimate Std. Error t-value Pr(>|t|)    \nprice   12557.58   11579.83    1.08     0.28    \neprice  -8425.45    5926.83   -1.42     0.16    \noprice    803.70    1000.90    0.80     0.42    \nlprice  12545.43   12460.36    1.01     0.32    \nheating    60.55      11.03    5.49  4.4e-07 ***\nincome     -2.03       5.67   -0.36     0.72    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    6.12e+10\nResidual Sum of Squares: 4.16e+10\nR-Squared:      0.32\nAdj. R-Squared: 0.0544\nF-statistic: 6.42587 on 6 and 82 DF, p-value: 0.000014\n```\n\n\n:::\n:::\n\n\nIn conclusion, from the analyses and tests that were run, we will implement the two-way fixed effect model as our preferred model. By controlling for both individual (state-specific) and time-specific unobserved heterogeneity, the model isolates the within-state, over-time variation in key variables such as energy prices, income, and weather (heating degree days). Heating degree days are highly significant, reaffirming the impact of climate on consumption. In contrast, income and prices show weaker within-state effects, suggesting that behavioral or structural consumption patterns are relatively stable in the short run. These findings could inform policy by emphasizing the limited short-run responsiveness of natural gas consumption to price signals. Instead structural changes such as updating energy efficiency standards or improving home insulation, may be more effective. Moreover, the large and significant role of heating degree days suggests that climate variability or change will continue to be a critical factor in energy planning and state-level resource allocation. A few limitations for our analyses include the small number of individual states as we only included 5 which limits the generalizability of the effects across states. \n\n",
    "supporting": [
      "03-project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}