{
  "hash": "b40f1bced1b2036346dcf103f0fc53a4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Economics 103 - Gym Members Exercise Tracking\"\nimage: ../gym_members.png\nauthor: \"Prisha Narasimhan\"\ndate: \"2025-10-15\"\noutput:\n  pdf_document: default\n  html_document: default\ndescription: |\n  <br>\n  This project built and refined a multiple regression model to understand how factors such as BMI, height, body composition, water intake, workout habits, and demographics influence weight. We applied log transformations, evaluated model assumptions, tested for multicollinearity, interactions, and misspecification, and validated the model through bootstrapping and cross-validation to identify the best-fitting and most reliable specification.\n---  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\ngym_members_exercise_tracking <- read_csv(\"~/Econ 103/gym_members_exercise_tracking.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 973 Columns: 15\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (2): Gender, Workout_Type\ndbl (13): Age, Weight (kg), Height (m), Max_BPM, Avg_BPM, Resting_BPM, Sessi...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndata = gym_members_exercise_tracking\n```\n:::\n\n\n# Model Building\n\nBasic Multiple Regression Model\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(`Weight (kg)` ~ BMI + `Height (m)` + Fat_Percentage + \n              `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n              Workout_Type, \n            data = gym_members_exercise_tracking)\nplot(model)\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-2-4.png){width=672}\n:::\n:::\n\n# Test for Transformations\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngym_members_exercise_tracking$log_Weight <- \n  log(gym_members_exercise_tracking$`Weight (kg)`)\ngym_members_exercise_tracking$log_BMI <- log(gym_members_exercise_tracking$BMI)\ngym_members_exercise_tracking$log_Height <- \n  log(gym_members_exercise_tracking$`Height (m)`)\n\nmodel_log <- lm(log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n                  `Water_Intake (liters)` + `Session_Duration (hours)` + Gender \n                + Workout_Type, \n                data = gym_members_exercise_tracking)\nsummary(model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.820e-04 -9.716e-05  5.880e-06  9.825e-05  4.012e-04 \n\nCoefficients:\n                             Estimate Std. Error   t value Pr(>|t|)    \n(Intercept)                -3.866e-05  9.642e-05    -0.401   0.6885    \nlog_BMI                     1.000e+00  1.845e-05 54203.765   <2e-16 ***\nlog_Height                  2.000e+00  7.789e-05 25676.470   <2e-16 ***\nFat_Percentage             -1.021e-07  1.002e-06    -0.102   0.9188    \n`Water_Intake (liters)`     9.701e-06  1.067e-05     0.909   0.3633    \n`Session_Duration (hours)` -2.476e-06  1.606e-05    -0.154   0.8775    \nGenderMale                 -2.850e-05  1.448e-05    -1.969   0.0493 *  \nWorkout_TypeHIIT           -5.324e-06  1.199e-05    -0.444   0.6570    \nWorkout_TypeStrength        3.372e-06  1.155e-05     0.292   0.7703    \nWorkout_TypeYoga            3.388e-06  1.176e-05     0.288   0.7734    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001301 on 963 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 4.924e+08 on 9 and 963 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n# Apply the 3 log transformations that we found necessary earlier. \n\nCandidate Model \n\n::: {.cell}\n\n```{.r .cell-code}\ncan_model <- lm(log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n                  `Water_Intake (liters)` + `Session_Duration (hours)` + Gender \n                + Workout_Type, \n                data = gym_members_exercise_tracking)\ncan_model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type, data = gym_members_exercise_tracking)\n\nCoefficients:\n               (Intercept)                     log_BMI  \n                -3.866e-05                   1.000e+00  \n                log_Height              Fat_Percentage  \n                 2.000e+00                  -1.021e-07  \n   `Water_Intake (liters)`  `Session_Duration (hours)`  \n                 9.701e-06                  -2.476e-06  \n                GenderMale            Workout_TypeHIIT  \n                -2.850e-05                  -5.324e-06  \n      Workout_TypeStrength            Workout_TypeYoga  \n                 3.372e-06                   3.388e-06  \n```\n\n\n:::\n:::\n\n\nBased on the tests run so far, the candidate model accounts for the necessary transformations required on the response and the predictors. With this candidate model, we are trying to find if there is a positive linear relationship between the response variable of weight and the 7 predictors (BMI, height, fat percentage, water intake, session duraction, gender, and workout type). This model is ideally able to take in the appropriately transformed variables and find if in fact there is such positive linear relationship as well as investigate other questions such as if there is multicollinearity between the factor variables and if certain predictors affect weight more than others. The above model is therefore the ideal candidate model to answer such questions. \n\n# Residual Plot Transformed Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model_log, which = 1)\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nResidual Plot is randomly scattered around 0, indicating a good plot. Compared to the untransformed data, the residuals of the candidate model appear much more evenly distributed around the horizontal line at 0. However, the only area of concern is that there appears to be a slight narrowing of the residuals as the fitted values increase, hinting that there may be larger variances for smaller values. \n\n# QQ Plot \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nqqPlot(model_log)\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 868 909\n```\n\n\n:::\n\n```{.r .cell-code}\noutlierTest(model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo Studentized residuals with Bonferroni p < 0.05\nLargest |rstudent|:\n    rstudent unadjusted p-value Bonferroni p\n909 3.126248          0.0018237           NA\n```\n\n\n:::\n:::\n\n\nQQ Plot follows a straight line in general, indicating a normal distribution. However, 868 and 909 appear to be outliers. However, checking with a Bonferroni outlier test shows that these are not significant outliers. \n\n# Jarque Bera Test\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tseries)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'quantmod':\n  method            from\n  as.zoo.data.frame zoo \n```\n\n\n:::\n\n```{.r .cell-code}\n# Jarque Bera Test for Untransformed Model\njarque.bera.test(model$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tJarque Bera Test\n\ndata:  model$residuals\nX-squared = 187.81, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Jarque Bera Test for Candidate Model\njarque.bera.test(model_log$residuals) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tJarque Bera Test\n\ndata:  model_log$residuals\nX-squared = 10.91, df = 2, p-value = 0.004274\n```\n\n\n:::\n:::\n\n\nUsing the residual plot for the candidate model, the qq-plot, and the Jarque Bera test, we see that there is no need for further transformations on the candidate model. While the Jarque Bera test p-value is rather low, the p-value for the transformed model is much larger than that of the untransformed model, and furthermore, based on the residual plot we may conclude that there is ultimately no need for further transformation as the scatter is overall random around the horizontal line at 0, indicating a more normal distribution. \n\n# Cook's Distance Plot\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\ninfluenceIndexPlot(model_log, id=list(n=3), vars = \"Cook\", \n                   main = \"Cook's Distance Plot (Top 3 Influential Points)\")\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe Cook's Distance Plot also identifies the same infuential points as the QQ Plot, 868 and 909 as well as point 170. \n\n# Outlier and Leverage Diagnostics\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(olsrr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'olsrr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:datasets':\n\n    rivers\n```\n\n\n:::\n\n```{.r .cell-code}\nols_plot_resid_lev(model_log)\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nConsidering the transformed residual plot, qq plot, Cook's distance plot, and the Outlier and Leverage Diagnostics, while there are outliers such as points 868, 909, and 170, they would not need to be removed. In the qqplot the outliers outlined are within the 95% confidence interval in addition to the Bonferroni outlier test which demonstrated that these outliers were not significant. Furthermore, as the residual plot of the candidate model is fairly scattered, suggesting that the model assumptions are upheld, the inclusion of the outliers does not appear to distort the overall randomness of the residuals. Therefore, it is reasonable to retain the outliers in this analysis. \n\n# AIC for Model Selection\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(POE5Rdata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'POE5Rdata'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:datasets':\n\n    euro\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_log.mod1 <- lm(log_Weight~ log_BMI, data = gym_members_exercise_tracking)\nmodel_log.mod2 <- lm(log_Weight~ log_BMI + log_Height, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod3 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod4 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)`, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod5 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)`, \n                data = gym_members_exercise_tracking)\nmodel_log.mod6 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)` + \n                       Gender, \n                data = gym_members_exercise_tracking)\nmodel_log.mod7 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)` + \n                       Gender + Workout_Type, \n                data = gym_members_exercise_tracking)\nAIC(model_log.mod1, model_log.mod2, model_log.mod3, model_log.mod4, \n    model_log.mod5, model_log.mod6, model_log.mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               df         AIC\nmodel_log.mod1  3   -994.0934\nmodel_log.mod2  4 -14647.7960\nmodel_log.mod3  5 -14645.8001\nmodel_log.mod4  6 -14643.8010\nmodel_log.mod5  7 -14641.9933\nmodel_log.mod6  8 -14643.7439\nmodel_log.mod7 11 -14638.4366\n```\n\n\n:::\n:::\n\n\nAccording to the AIC model, the preferred model is Model 2, which only includes BMI and height. \n\n# BIC for Model Selection\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(POE5Rdata)\nmodel_log.mod1 <- lm(log_Weight~ log_BMI, data = gym_members_exercise_tracking)\nmodel_log.mod2 <- lm(log_Weight~ log_BMI + log_Height, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod3 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod4 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)`, \n                     data = gym_members_exercise_tracking)\nmodel_log.mod5 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)`, \n                data = gym_members_exercise_tracking)\nmodel_log.mod6 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)` + \n                       Gender, \n                data = gym_members_exercise_tracking)\nmodel_log.mod7 <- lm(log_Weight~ log_BMI + log_Height + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)` + \n                       Gender + Workout_Type, \n                data = gym_members_exercise_tracking)\nBIC(model_log.mod1, model_log.mod2, model_log.mod3, model_log.mod4, \n    model_log.mod5, model_log.mod6, model_log.mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               df         BIC\nmodel_log.mod1  3   -979.4523\nmodel_log.mod2  4 -14628.2745\nmodel_log.mod3  5 -14621.3982\nmodel_log.mod4  6 -14614.5187\nmodel_log.mod5  7 -14607.8306\nmodel_log.mod6  8 -14604.7008\nmodel_log.mod7 11 -14584.7524\n```\n\n\n:::\n:::\n\n\nAccording to the BIC model, the preferred model is Model 2, which only includes BMI and height. \n\n# Multicollinearity \n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nvif(model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               GVIF Df GVIF^(1/(2*Df))\nlog_BMI                    1.353499  1        1.163400\nlog_Height                 1.886661  1        1.373558\nFat_Percentage             2.258214  1        1.502735\n`Water_Intake (liters)`    2.354351  1        1.534389\n`Session_Duration (hours)` 1.743597  1        1.320453\nGender                     3.006329  1        1.733877\nWorkout_Type               1.022472  3        1.003711\n```\n\n\n:::\n:::\n\n\nUsing threshold 4, we keep all variables. \n\n# Compare Transformed Model to Original\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_original <- lm(`Weight (kg)` ~ BMI + `Height (m)` + Fat_Percentage + \n                       `Water_Intake (liters)` + `Session_Duration (hours)` + \n                       Gender + Workout_Type, \n                     data = gym_members_exercise_tracking)\n\nAIC(model_original, model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               df        AIC\nmodel_original 11   4559.816\nmodel_log      11 -14638.437\n```\n\n\n:::\n\n```{.r .cell-code}\nBIC(model_original, model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               df        BIC\nmodel_original 11   4613.501\nmodel_log      11 -14584.752\n```\n\n\n:::\n:::\n\n\nA Lower AIC and BIC Indicate a better fit compared to the original model. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_log_weight <- predict(model_log, gym_members_exercise_tracking)\nactual_log_weight <- gym_members_exercise_tracking$log_Weight\n\nplot(predicted_log_weight, actual_log_weight, main = \"Predicted vs Actual\n     (Log-Transformed Weight)\",\n     xlab = \"Predicted Log Weight\", ylab = \"Actual Log Weight\", col = \"blue\")\nabline(0, 1, col = \"red\") \n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nAlso by visualizing the data we can see that the transformed model does a good job. I tested for multicollinearity by using the VIF method, and based on the threshold of 4, we do not need to remove any of the variables. Furthermore, comparing the AIC and BIC values for the untransformed data to the transformed candidate model, the canidate model seems to have a much better fit as AIC and BIC value is far smaller. Finally, we compared our candidate model to the actual data which was fairly aligned indicating that the model is a good fit of the data.\n\n# Model Misspecification Ramsey Reset\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nlibrary(POE5Rdata)\nlibrary(lmtest)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: zoo\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'zoo'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n```\n\n\n:::\n\n```{.r .cell-code}\nreset_test <- resettest(model_log, power = 2:3, type = \"fitted\")\nprint(reset_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  model_log\nRESET = 1.1687, df1 = 2, df2 = 961, p-value = 0.3112\n```\n\n\n:::\n:::\n\n\nBy running the RESET test, we see that the P-Value of 0.3112 is large enough at the 95% confidence level to fail to reject the null, so a nonlinear term is not needed. This indicates that there is no strong evidence to suggest that important unobserved variables are omitted from the model. Moreover, this implies that the candidate model is likely appropriate for understanding the relationship between the response variable, weight,and the predictor variables.\n\n# Test for Interaction Terms\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(POE5Rdata)\nlibrary(effects)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_log1 <- lm(log_Weight~log_BMI+log_Height+Fat_Percentage+\n                   `Water_Intake (liters)`+`Session_Duration (hours)`+ `Gender` + `Workout_Type` + log_BMI:log_Height, data = gym_members_exercise_tracking)\nmodel_log2 <- lm(log_Weight~log_BMI+log_Height+Fat_Percentage+\n                   `Water_Intake (liters)`+`Session_Duration (hours)`+ `Gender` + `Workout_Type`+ log_Height:Fat_Percentage, data = gym_members_exercise_tracking)\nmodel_log3 <- lm(log_Weight~log_BMI+log_Height+Fat_Percentage+\n                   `Water_Intake (liters)`+`Session_Duration (hours)`+ `Gender` + `Workout_Type` + `Water_Intake (liters)`:Fat_Percentage, data = gym_members_exercise_tracking)\nmodel_log4 <- lm(log_Weight~log_BMI+log_Height+Fat_Percentage+\n                   `Water_Intake (liters)`+`Session_Duration (hours)`+ `Gender` + `Workout_Type` + `Gender`:`Workout_Type` , data = gym_members_exercise_tracking)\n\nsummary(model_log1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type + log_BMI:log_Height, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.832e-04 -9.782e-05  5.300e-06  9.703e-05  3.803e-04 \n\nCoefficients:\n                             Estimate Std. Error  t value Pr(>|t|)    \n(Intercept)                -4.785e-04  4.500e-04   -1.063   0.2879    \nlog_BMI                     1.000e+00  1.379e-04 7252.725   <2e-16 ***\nlog_Height                  2.001e+00  7.940e-04 2520.028   <2e-16 ***\nFat_Percentage             -9.340e-08  1.002e-06   -0.093   0.9257    \n`Water_Intake (liters)`     9.812e-06  1.067e-05    0.920   0.3579    \n`Session_Duration (hours)` -2.831e-06  1.606e-05   -0.176   0.8601    \nGenderMale                 -3.046e-05  1.461e-05   -2.085   0.0373 *  \nWorkout_TypeHIIT           -4.689e-06  1.200e-05   -0.391   0.6961    \nWorkout_TypeStrength        3.581e-06  1.155e-05    0.310   0.7565    \nWorkout_TypeYoga            3.955e-06  1.178e-05    0.336   0.7371    \nlog_BMI:log_Height         -2.459e-04  2.457e-04   -1.001   0.3172    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001301 on 962 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 4.432e+08 on 10 and 962 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_log2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type + log_Height:Fat_Percentage, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.832e-04 -9.723e-05  5.990e-06  9.800e-05  3.976e-04 \n\nCoefficients:\n                             Estimate Std. Error   t value Pr(>|t|)    \n(Intercept)                 6.600e-05  1.539e-04     0.429   0.6681    \nlog_BMI                     1.000e+00  1.845e-05 54189.753   <2e-16 ***\nlog_Height                  2.000e+00  2.338e-04  8553.943   <2e-16 ***\nFat_Percentage             -4.460e-06  5.094e-06    -0.876   0.3815    \n`Water_Intake (liters)`     9.809e-06  1.067e-05     0.919   0.3581    \n`Session_Duration (hours)` -2.400e-06  1.606e-05    -0.149   0.8812    \nGenderMale                 -2.948e-05  1.452e-05    -2.030   0.0427 *  \nWorkout_TypeHIIT           -5.365e-06  1.199e-05    -0.448   0.6546    \nWorkout_TypeStrength        3.012e-06  1.156e-05     0.261   0.7944    \nWorkout_TypeYoga            3.044e-06  1.177e-05     0.259   0.7960    \nlog_Height:Fat_Percentage   8.036e-06  9.210e-06     0.873   0.3831    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001301 on 962 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 4.431e+08 on 10 and 962 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_log3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type + `Water_Intake (liters)`:Fat_Percentage, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.816e-04 -9.735e-05  5.100e-06  9.679e-05  4.013e-04 \n\nCoefficients:\n                                         Estimate Std. Error   t value Pr(>|t|)\n(Intercept)                            -5.675e-05  1.310e-04    -0.433   0.6649\nlog_BMI                                 1.000e+00  1.846e-05 54164.065   <2e-16\nlog_Height                              2.000e+00  7.801e-05 25638.184   <2e-16\nFat_Percentage                          6.245e-07  3.697e-06     0.169   0.8659\n`Water_Intake (liters)`                 1.624e-05  3.376e-05     0.481   0.6306\n`Session_Duration (hours)`             -2.959e-06  1.624e-05    -0.182   0.8555\nGenderMale                             -2.824e-05  1.454e-05    -1.942   0.0524\nWorkout_TypeHIIT                       -5.392e-06  1.200e-05    -0.449   0.6532\nWorkout_TypeStrength                    3.395e-06  1.155e-05     0.294   0.7689\nWorkout_TypeYoga                        3.451e-06  1.177e-05     0.293   0.7694\nFat_Percentage:`Water_Intake (liters)` -2.544e-07  1.246e-06    -0.204   0.8383\n                                          \n(Intercept)                               \nlog_BMI                                ***\nlog_Height                             ***\nFat_Percentage                            \n`Water_Intake (liters)`                   \n`Session_Duration (hours)`                \nGenderMale                             .  \nWorkout_TypeHIIT                          \nWorkout_TypeStrength                      \nWorkout_TypeYoga                          \nFat_Percentage:`Water_Intake (liters)`    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001301 on 962 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 4.427e+08 on 10 and 962 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_log4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type + Gender:Workout_Type, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.801e-04 -9.750e-05  5.400e-06  9.779e-05  3.999e-04 \n\nCoefficients:\n                                  Estimate Std. Error   t value Pr(>|t|)    \n(Intercept)                     -3.644e-05  9.693e-05    -0.376    0.707    \nlog_BMI                          1.000e+00  1.852e-05 53988.484   <2e-16 ***\nlog_Height                       2.000e+00  7.815e-05 25591.518   <2e-16 ***\nFat_Percentage                  -1.247e-07  1.003e-06    -0.124    0.901    \n`Water_Intake (liters)`          9.815e-06  1.068e-05     0.919    0.358    \n`Session_Duration (hours)`      -2.958e-06  1.609e-05    -0.184    0.854    \nGenderMale                      -2.049e-05  2.002e-05    -1.024    0.306    \nWorkout_TypeHIIT                -2.160e-06  1.715e-05    -0.126    0.900    \nWorkout_TypeStrength             1.422e-05  1.656e-05     0.859    0.391    \nWorkout_TypeYoga                 4.718e-06  1.722e-05     0.274    0.784    \nGenderMale:Workout_TypeHIIT     -6.286e-06  2.398e-05    -0.262    0.793    \nGenderMale:Workout_TypeStrength -2.103e-05  2.306e-05    -0.912    0.362    \nGenderMale:Workout_TypeYoga     -3.148e-06  2.355e-05    -0.134    0.894    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001302 on 960 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 3.685e+08 on 12 and 960 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nUsing the p-value of coefficients, we see that the model is not statistically significant among the interaction terms, so we won't need to include them.\n\n# Bootstrapping Log Transformed Model with Interaction Variable\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'boot'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:POE5Rdata':\n\n    tuna\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:car':\n\n    logit\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nbootstrap_function <- function(data, indices) {\n  resampled_data <- data[indices, ]\n\n  model_resampled <- lm(log_Weight ~ log_BMI * Fat_Percentage + log_Height + \n                        `Water_Intake (liters)` + `Session_Duration (hours)`, \n                        data = resampled_data)\n  return(coef(model_resampled))  }\nset.seed(123) \nboot_results <- boot(data = gym_members_exercise_tracking, statistic = bootstrap_function, R = 1000)\nboot_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nORDINARY NONPARAMETRIC BOOTSTRAP\n\n\nCall:\nboot(data = gym_members_exercise_tracking, statistic = bootstrap_function, \n    R = 1000)\n\n\nBootstrap Statistics :\n         original        bias     std. error\nt1* -5.882657e-04 -8.554770e-06 3.014201e-04\nt2*  1.000187e+00  2.631089e-06 8.886319e-05\nt3*  2.423869e-05  2.404932e-07 1.133134e-05\nt4*  1.999968e+00  8.871506e-07 6.440787e-05\nt5* -1.338986e-06 -5.953335e-08 9.266424e-06\nt6*  7.157967e-06 -1.077169e-07 1.619223e-05\nt7* -7.503450e-06 -7.659321e-08 3.458305e-06\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(boot_results$t) <- names(coef(lm(log_Weight ~ log_BMI * Fat_Percentage + log_Height + \n                                         `Water_Intake (liters)` + `Session_Duration (hours)`, \n                                         data = gym_members_exercise_tracking)))\n\ninteraction_coefficients <- boot_results$t[, \"log_BMI:Fat_Percentage\"]\n\nhist(interaction_coefficients, \n     main = \"Bootstrap Distribution of log_BMI:Fat_Percentage Interaction Coefficient\", \n     xlab = \"Interaction Coefficient (log_BMI:Fat_Percentage)\", \n     col = \"lightblue\", \n     border = \"black\", \n     breaks = 30)\n```\n\n::: {.cell-output-display}\n![](05-project_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe Histogram looks fairly symmetric and normally distributed. Based on this histogram, the sampling distribution of the predictors are overall approximately normal, which suggests that the inference methods relying on normality may still be reasonably robust. \n\n# Cross Validation\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(caret)) install.packages(\"caret\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: caret\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: lattice\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'lattice'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:boot':\n\n    melanoma\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(caret)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) \ncv_control <- trainControl(method = \"cv\", number = 10)\n\ncv_model <- train(log_Weight ~ log_BMI * Fat_Percentage + log_Height + \n                  `Water_Intake (liters)` + `Session_Duration (hours)`, \n                  data = gym_members_exercise_tracking, \n                  method = \"lm\",  \n                  trControl = cv_control)\nprint(cv_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear Regression \n\n973 samples\n  5 predictor\n\nNo pre-processing\nResampling: Cross-Validated (10 fold) \nSummary of sample sizes: 875, 874, 876, 876, 876, 876, ... \nResampling results:\n\n  RMSE          Rsquared   MAE         \n  0.0001299402  0.9999998  0.0001083176\n\nTuning parameter 'intercept' was held constant at a value of TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cross-Validated RMSE:\", cv_model$results$RMSE, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-Validated RMSE: 0.0001299402 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cross-Validated R-Squared:\", cv_model$results$Rsquared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCross-Validated R-Squared: 0.9999998 \n```\n\n\n:::\n:::\n\n\nRMSE of 0.0001299402 suggests that the model's predictions of log_Weight deviate only slightly from the observed values. An R-squared value of 0.9999998 means that nearly all the variability in log_Weight is explained by the predictors, including the interaction term. A MAE of 0.0001083176 is very close to zero, further confirming the model's strong predictive power.\n\n# Check for Overfitting since R-squared value is so high\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ntrain_indices <- createDataPartition(gym_members_exercise_tracking$log_Weight, p = 0.8, list = FALSE)\ntraining_data <- gym_members_exercise_tracking[train_indices, ]\ntesting_data <- gym_members_exercise_tracking[-train_indices, ]\n\nmodel_train <- lm(log_Weight ~ log_BMI * Fat_Percentage + log_Height + \n                  `Water_Intake (liters)` + `Session_Duration (hours)`, \n                  data = training_data)\n\ntrain_predictions <- predict(model_train, newdata = training_data)\ntrain_rmse <- sqrt(mean((train_predictions - training_data$log_Weight)^2))\ntrain_r2 <- 1 - sum((train_predictions - training_data$log_Weight)^2) / \n                sum((training_data$log_Weight - mean(training_data$log_Weight))^2)\n\ncat(\"Training RMSE:\", train_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining RMSE: 0.0001309695 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Training R²:\", train_r2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining R²: 0.9999998 \n```\n\n\n:::\n\n```{.r .cell-code}\ntest_predictions <- predict(model_train, newdata = testing_data)\ntest_rmse <- sqrt(mean((test_predictions - testing_data$log_Weight)^2))\ntest_r2 <- 1 - sum((test_predictions - testing_data$log_Weight)^2) / \n               sum((testing_data$log_Weight - mean(testing_data$log_Weight))^2)\n\ncat(\"Test RMSE:\", test_rmse, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTest RMSE: 0.0001237238 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Test R²:\", test_r2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTest R²: 0.9999998 \n```\n\n\n:::\n:::\n\n\nThe slightly lower RMSE on the test set (0.0001237238) suggests that the model generalizes very well to unseen data and does not overfit. The identical R² values for both the training and test sets suggest that the model performs equally well on unseen data as it does on the data it was trained on, confirming no signs of overfitting.\n\n# Favorite Specification\n\nIn our analysis, using the Jarque Bera test, the qq plot, and the residual plot of the candidate model, we found that there is no need for further transformations on our model. Based on the Cook's Distance plot, the Outlier and Leverage Diagnostic plot, with inferences from the residual plot, we noted that while there are outliers in our model, they do not need to be removed. Using the AIC and BIC model, along with the VIF method, we tested for multicollinearity and noted that no variables needed to be removed. To test model misspecification, we ran the RESET test and as the p-value was not statistically significant, we concluded that nonlinear terms were not needed in the model. We additionally tested interactions between variables and found that there were no significant interactions to include amongst the ones tested. Finally, using the boostrap method, the resulting histogram was overall normally distributed resulting in a reasonable amount of robustness. A preferred form of analysis was the RESET test, as it's p-value indicated whether nonlinear terms were needed in the model, and furthermore if there were any unobserved omitted variables (which may have been the cause if the p-value was below 0.05). This test incorporates our understanding of the p-value to test specific characteristics on the model and encourage changes such as a quardratic variable or to think further about unobserved variables when the p-value is significant. \n\n# Conclusion\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_Weight ~ log_BMI + log_Height + Fat_Percentage + \n    `Water_Intake (liters)` + `Session_Duration (hours)` + Gender + \n    Workout_Type, data = gym_members_exercise_tracking)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.820e-04 -9.716e-05  5.880e-06  9.825e-05  4.012e-04 \n\nCoefficients:\n                             Estimate Std. Error   t value Pr(>|t|)    \n(Intercept)                -3.866e-05  9.642e-05    -0.401   0.6885    \nlog_BMI                     1.000e+00  1.845e-05 54203.765   <2e-16 ***\nlog_Height                  2.000e+00  7.789e-05 25676.470   <2e-16 ***\nFat_Percentage             -1.021e-07  1.002e-06    -0.102   0.9188    \n`Water_Intake (liters)`     9.701e-06  1.067e-05     0.909   0.3633    \n`Session_Duration (hours)` -2.476e-06  1.606e-05    -0.154   0.8775    \nGenderMale                 -2.850e-05  1.448e-05    -1.969   0.0493 *  \nWorkout_TypeHIIT           -5.324e-06  1.199e-05    -0.444   0.6570    \nWorkout_TypeStrength        3.372e-06  1.155e-05     0.292   0.7703    \nWorkout_TypeYoga            3.388e-06  1.176e-05     0.288   0.7734    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0001301 on 963 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 4.924e+08 on 9 and 963 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nUpon building and testing our model through various forms of analysis, we may now use it to help answer some of our motivating questions. Using the estimated values shown in the above summary of our model, we are able to observe whether there is a linear relationship between our reponse variable weight, and each of the seven predictors. We notice that BMI and Height have a positive linear relationship with weight therefore the marginal effect from an increase in either of these variables will have an increase in weight as well. This may be due to the fact that BMI and Height have a direct relationship with weight as BMI times Height (m)^2 is equal to weight, indicating a direct positive relationship. BMI and Height therefore seem to have a stronger relationship to weight, which is further assured by AIC and BIC models in which the preferred model included only BMI and Height. Additionally, from our model, we observe that Water Intake (liters), Strength Workouts and Yoga Workout, have a positive linear relationship with weight (based on their marginal effects), suggesting that increased water intake, a higher frequency of strength and yoga workouts may be associated with higher weight when considered marginally.  Fat percentage, gender (male), Session duration, and HIIT Workout have negative marginal effects in relation to weight. This suggests that these variables are associated with reductions in weight when considered marginally. ",
    "supporting": [
      "05-project_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}